// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkrbnntnsyavphpmulfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrcmJubnRuc3lhdnBocG11bGZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNjgzNzUsImV4cCI6MjA1Mzg0NDM3NX0.guQeEsIkPwpqxcifCw9mPJGLY1h7-cnt-1tF6Mqj6iE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);